### ISSUE TITLE
Corrigir atualizar cliente com id inexistente

### ISSUE THREAD

**Issue by oliveiralex** [fonaziero/CRUD#1]
Olá, tudo bem? Sou o Alexandre e estou corrigindo a sua atividade.

Seu trabalho já está aceito, parabéns! Para ficar 100% eu sugiro, incluir o tratamento de exceções. Ao atualizar um cliente com id inexistente retorna um erro 500.

Abraço e bons estudos

**Comment by fonaziero** [comment]
Muito obrigado Alexandre pelo feedback !!!
irei adicionar a exceção 😉

**Comment by fonaziero** [comment]
> Olá, tudo bem? Sou o Alexandre e estou corrigindo a sua atividade.
> 
> Seu trabalho já está aceito, parabéns! Para ficar 100% eu sugiro, incluir o tratamento de exceções. Ao atualizar um cliente com id inexistente retorna um erro 500.
> 
> Abraço e bons estudos

**Comment by fonaziero** [comment]
> Olá, tudo bem? Sou o Alexandre e estou corrigindo a sua atividade.
> 
> Seu trabalho já está aceito, parabéns! Para ficar 100% eu sugiro, incluir o tratamento de exceções. Ao atualizar um cliente com id inexistente retorna um erro 500.
> 
> Abraço e bons estudos

**Comment by fonaziero** [comment]
![image](https://user-images.githubusercontent.com/62632271/119709761-f2243200-be33-11eb-8639-3c6b78612b97.png)

Fixed !
